### ISSUE TITLE
RFN, onboarding to Google Fonts

### ISSUE THREAD

**Issue by yanone** [figs-lab/datalegreya#14]
Hello.

I've been commissioned to onboard Datalegreya to Google Fonts. Before discussing changes to technical details, Google Fonts requires the removal of the RFN, as fonts do get modified (by subsetting) when delivered through the Google Fonts Webfont API.

There is a section regarding RFN in the GF Guide: https://googlefonts.github.io/gf-guide/license-file.html#requirements

Please use the email template given there to authorize Google to use the font. For questions, please  also email fonts@google.com. (I'm only involved in technical work, not legal)

Thank you so much.

**Comment by olicorn** [comment]
Hello Yanone,
thank you very much for doing this.
I have send the email to ***@***.*** following the template
Kind regards
Olivier

**Comment by davelab6** [comment]
Confirmed, thanks!

**Comment by yanone** [comment]
Closing because permission has been granted.
