### ISSUE TITLE
Lines without dots?

### ISSUE THREAD

**Issue by peterbrinck** [figs-lab/datalegreya#5]
This is a really nice font!
Extremely font to play with and can be used in so many different ways

But.. I was wondering, how I can "turn off" the dots under the lines?
Like on your website

![With Dots](https://cloud.githubusercontent.com/assets/6154068/20791273/709803ec-b7bc-11e6-913b-b5554aeda120.png)

![Without Dots On Your Website](https://cloud.githubusercontent.com/assets/6154068/20791295/89231212-b7bc-11e6-8e6f-34e38bd75c3e.png)

**Comment by timotheegoguely** [comment]
Hi @peterbrinck ! Thank you for reaching us.

You can’t "turn off" on our demo website right now (but certainly in a future update), but if you download the repository, you can use any of the 3 available fonts: Dot, Gradient, Thin.

Does it answer your question?

**Comment by peterbrinck** [comment]
I see!
I didn't even look for it in the files, thanks :smile:

**Comment by timotheegoguely** [comment]
Thanks to @ChrisGitIt, you can now test the 3 different fonts on our [conversion tool page](http://www.figs-lab.com/content/datalegreya/convert.html) 😉

**Comment by peterbrinck** [comment]
Great, thanks both of you! :smiley:
